// Mocks generated by Mockito 5.3.2 from annotations
// in git_hub/test/provider/repositories_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:git_hub/models/get_repositories/repository_response.dart' as _i4;
import 'package:git_hub/repository/get_repositories_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetRepositoriesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRepositoriesRepo extends _i1.Mock implements _i2.GetRepositoriesRepo {
  MockGetRepositoriesRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RepositoryResponse>> getRepositories({required String? language}) => (super.noSuchMethod(
        Invocation.method(
          #getRepositories,
          [],
          {#language: language},
        ),
        returnValue: _i3.Future<List<_i4.RepositoryResponse>>.value(<_i4.RepositoryResponse>[]),
      ) as _i3.Future<List<_i4.RepositoryResponse>>);
}
